### ISSUE TITLE
Code doesn't work in VS 2013

### ISSUE THREAD

**Issue by ddsmith99301** [stimulsoft/Samples-Dashboards-WinForms-CSharp#1]
In DashboardDemoForm.cs I am getting an error on this line. It doesn't like the =>. Something must be missing in the Lambda expression.

public List<StiDashboard> Dashboards => Report?.Pages.OfType<StiDashboard>().Where(d => d.Enabled).ToList();

**Comment by VladimirBLR** [comment]
Hello, 

We only support Visual Studio 2015+ and .NET Framework 4.5+

**Comment by ddsmith99301** [comment]
Please let me know how to interpret this line of code. All other code works in VS2013, but this.

public List<StiDashboard> Dashboards => Report?.Pages.OfType<StiDashboard>().Where(d => d.Enabled).ToList();

**Comment by VladimirBLR** [comment]
You can try using the "foreach" for report pages, check the type for StiDashboard and the Enabled flag for pages, and add only those that have the StiDashboard type and Enabled = true to the collection.

Thank you.

**Comment by ddsmith99301** [comment]
Thank you! That worked.
